/* smc_render_opt.h — adapter layer for Self-Modifying Calculator renderer optimization
 *
 * This header provides a small, isolated interface between the raycasting
 * renderer and the generated SMC dispatch table.  All SMC usage in the
 * renderer goes through this adapter so that SMC can be disabled at build
 * time with USE_SMC=0.
 *
 * When USE_SMC is defined, the adapter initializes the SMC runtime on first
 * use and exposes thin wrappers around smc_call_double for the specific
 * renderer expressions we have generated.  When USE_SMC is not defined, the
 * macros/functions fall back to the original C math.
 */

#ifndef SMC_RENDER_OPT_H
#define SMC_RENDER_OPT_H

#include "config.h"   /* for config_get() if needed */
#include <math.h>
#include <stddef.h>
#include <stdint.h>

#ifdef USE_SMC
#include "smc.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Initialize the SMC runtime and verify that the generated table contains the
 * expressions the renderer expects.  Safe to call multiple times; returns 0 on
 * success.  When USE_SMC is not defined this is a no-op that returns 0. */
int smc_render_opt_init(void);

/* Shutdown the SMC runtime.  No-op when USE_SMC is not defined. */
void smc_render_opt_shutdown(void);

/* Reset SMC statistics counters.  No-op when USE_SMC is not defined. */
void smc_render_opt_reset_stats(void);

/* Fill OUT with a snapshot of SMC statistics.  No-op when USE_SMC is not
 * defined (all counters stay zero). */
void smc_render_opt_get_stats(uint64_t *total_calls,
                              uint64_t *fallback_calls,
                              uint64_t *arity_errors,
                              uint64_t *invalid_ids);

/* --------------------------------------------------------------------------
 *  Hot-path wrappers.  These match the expressions generated by
 *  scripts/generate-smc-renderer.lisp.
 * -------------------------------------------------------------------------- */

/* Ray angle per column: atan(camera_x * tan(fov / 2.0))
 *   args: camera_x, fov
 *   result: angle offset in radians */
double smc_ray_angle_offset(double camera_x, double fov);

/* Fisheye correction: dist * cos(ray_angle - cam_angle)
 *   args: dist, ray_angle, cam_angle
 *   result: perpendicular (camera-forward) distance */
double smc_fisheye_correct(double dist, double ray_angle, double cam_angle);

/* Ceiling/floor true distance: currentDist / cos(ray_angle - cam_angle)
 *   args: currentDist, ray_angle, cam_angle
 *   result: world-space distance along the ray */
double smc_true_distance(double currentDist, double ray_angle, double cam_angle);

/* Light billboard screen X: tan(angle_diff) / tan(fov / 2.0)
 *   args: angle_diff, fov
 *   result: normalised screen X in [-1, 1] approximately */
double smc_light_screen_x(double angle_diff, double fov);

#ifdef __cplusplus
}
#endif

#endif /* SMC_RENDER_OPT_H */
